### ISSUE TITLE
Foursquare example

### ISSUE THREAD

**Issue by anildigital** [clojusc/friend-oauth2-examples#10]
I am trying to integrate with Foursquare but I am getting redirected to

http://localhost:3000/auth/callback?code=VUUJP3XHVB3UE3GZSQ3KCKZL5EBVBSXEC0V1YQDGZ2TIHAM4&state=sHpjq6ziK00bzy%2BQc4Nb%2Bw3%2BZy4X0diBFJozdgm4G1o3BEnzEPt9YccZM3dkKcAadXapoDzqlCRvNG#_=_

Looks like it's not fetching accessToken.

Here is the gist https://gist.github.com/anildigital/25bf4c6ecd69d4175d31

I am not sure why fetching accessToken flow is so hidden there.

**Comment by oubiwann** [comment]
There are some changes that have happened recently with friend-oauth2 and the examples -- primarily:
 * the friend-oauth2 repo is now maintained here: https://github.com/clojusc/friend-oauth2
 * the examples are now included in the friend-oauth2 repo itself, not in a separate repo

I haven't tried your gist, but am assuming it's still an issue? I'm going to copy this issue there -- let me know if this has been fixed, in which case I'll close it.

**Comment by oubiwann** [comment]
This ticket has been copied here:
 * https://github.com/clojusc/friend-oauth2/issues/58

As such, I am closing this one.
